x-logging:
  &logging
  logging:
    options:
      max-size: 50m
      max-file: "3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "traefik_letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ipallowlist.ipallowlist.sourcerange=$WHITELIST"


  arb-classic:
    #image: kw1k/arbnode:latest
    image: offchainlabs/arb-node:v1.4.5-e97c1a4
    container_name: arb-classic
    user: root
    restart: unless-stopped
    stop_grace_period: 3m
    env_file:
      - .env
    volumes:
      - "./arb-classic:/root/.arbitrum/mainnet"
    expose:
      - 8547
      - 8548
    command: |
      --l1.url=${L1_URL}
      --node.chain-id=42161
      --l2.disable-upstream
      --node.cache.allow-slow-lookup
      --node.rpc.tracing.enable
      --core.checkpoint-gas-frequency=156250000
      --core.lazy-load-core-machine
      --node.rpc.enable-l1-calls
    ##--l2.final-classic-block=22207816
    <<: *logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.arb-classic.loadbalancer.server.port=8547"
      - "traefik.http.routers.arb-classic.entrypoints=websecure"
      - "traefik.http.routers.arb-classic.tls.certresolver=myresolver"
      - "traefik.http.routers.arb-classic.rule=Host(`$CLASSIC_DOMAIN`)"
      - "traefik.http.routers.arb-classic.middlewares=ipallowlist"


  arb-nitro:
    image: offchainlabs/nitro-node:$NITRO_VERSION
    user: root
    restart: unless-stopped
    container_name: arb-nitro
    stop_grace_period: 3m
    env_file:
      - .env
    expose:
      - 8547
      - 8548
    volumes:
      - ./arb-nitro:/root/.arbitrum
    command: |
      --parent-chain.connection.url=${L1_URL}
      --chain.id=42161
      --http.api=net,web3,eth,debug
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.vhosts=*
      --execution.caching.archive
      --execution.rpc.classic-redirect=http://arb-classic:8547
    <<: *logging
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.arb.loadbalancer.server.port=8547"
    - "traefik.http.routers.arb.entrypoints=websecure"
    - "traefik.http.routers.arb.tls.certresolver=myresolver"
    - "traefik.http.routers.arb.rule=Host(`$DOMAIN`)"
    - "traefik.http.routers.arb.middlewares=ipallowlist"

volumes:
  traefik_letsencrypt:
